#!/bin/bash

SERVER_LOCATION=/home/filip/Dropbox/JavaProjects/oscillogscope

#################
#---FUNCTIONS---#
#################

function run_server {

cd $SERVER_LOCATION

mvn package

heroku local web -p 8080

}

##############
#---SCRIPT---#
##############

npm run production

cp dist/index.html $SERVER_LOCATION/src/main/resources/webapp/index.html
cp dist/index_bundle.js $SERVER_LOCATION//src/main/resources/webapp/index_bundle.js

run_server

exit 0
